spring:
  config:
    activate:
      on-profile: qa


build :
  version : QA_CARD_V1

cards:
  message: "Welcome to DSRTECHSOL CARDS related QA --- APIs "
  contactDetails:
    name: "GANESH - Developer"
    email: "ganesh@dsrtechsol.com"
  onCallSupport:
    - (108) 108-1008
    - (108) 108-1008

